limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Content-Security-Policy "default-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://product-review-static1.s3.amazonaws.com https://product-review-static1.s3.ap-northeast-2.amazonaws.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://product-review-static1.s3.amazonaws.com https://product-review-static1.s3.ap-northeast-2.amazonaws.com; connect-src 'self' https://cdn.jsdelivr.net; img-src 'self' data: https://product-review-static1.s3.amazonaws.com https://product-review-static1.s3.ap-northeast-2.amazonaws.com https://product-review-media1.s3.amazonaws.com https://product-review-media1.s3.ap-northeast-2.amazonaws.com; font-src 'self' data: https://product-review-static1.s3.amazonaws.com https://product-review-static1.s3.ap-northeast-2.amazonaws.com;" always;
    server_tokens off;

    location ~* \.php$ {
        return 444;
    }

    location ~* /(wp-admin|phpunit|vendor|cgi-bin|backup|\.env) {
        return 444;
    }

    location ~ /\. {
        deny all;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /ai/ {
        proxy_pass http://fastapi-server:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        limit_req zone=one burst=10 nodelay;
    }

    location / {
        proxy_pass http://drf-web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        limit_req zone=one burst=10 nodelay;
    }
}
